### ISSUE TITLE
site differs from template

### ISSUE THREAD

**Issue by Bombenleger** [arc42/docs.arc42.org-site#36]
There is a typo on the site: [section-3.md](https://github.com/arc42/docs.arc42.org-site/blame/master/_pages/section-3.md#L34), but it has been fixed in the template-repository already [03_system_scope_and_context.adoc](https://github.com/arc42/arc42-template/blame/master/EN/asciidoc/src/03_system_scope_and_context.adoc#L33)

Seems like that change was never brought to the site. Maybe this is just an example and there are more of these issues. Unfortunately I'm unable to find out why that happened.

**Comment by gernotstarke** [comment]
we maintain the arc42 template itself in AsciiDoc, but the (Jekyll-based) documentation site(s) are currently limited to Markdown.
We never implemented any automatic translation, but made this a manual effort, therefore it will surely contain bugs.
