### ISSUE TITLE
Missing pictures on various examples

### ISSUE THREAD

**Issue by c0ffee** [arc42/docs.arc42.org-site#71]
e.g.
https://docs.arc42.org/examples/buildingblock-2/
https://docs.arc42.org/examples/overview-example-3/
...

seems like all related to the "TrafficPursuitUnit"

**Comment by c0ffee** [comment]
in the repo the folder is uppercase "TPU" in the delivered links lower case

**Comment by gernotstarke** [comment]
should be fixed by now. Was a strange combination of uppercase/lowercase and different behavior on Github-server and local docker-based jekyll...

Thanx @c0ffee for pointing it out!
