### ISSUE TITLE
Example link goes to the wrong place

### ISSUE THREAD

**Issue by jean** [arc42/docs.arc42.org-site#79]
On https://docs.arc42.org/section-2/ there is a link "Example Constraints: HTML Sanity Checker" that goes to https://docs.arc42.org/examples/constraints-1/#2-constraints-for-html-sanity-checker which is blank. 

The proper target seems to be https://hsc.aim42.org/documentation/hsc_arc42.html#_constraints

**Comment by gernotstarke** [comment]
thanx - will have a look asap

**Comment by gernotstarke** [comment]
fixed with 522d2d6fd2e6f2bb04834fbc2aecf408cca1ad39
