### ISSUE TITLE
[SPELL] *you* instead of *your* in the *lean* paragraph on the homepage

### ISSUE THREAD

**Issue by mhatzl** [arc42/docs.arc42.org-site#97]
The first sentence in the *lean* paragraph on the homepage uses 

`... or streamline you documentation ...`

instead of 

`... or streamline your documentation ...`

See screenshot:

![image](https://user-images.githubusercontent.com/49341624/214395191-ee198ede-c930-46c3-a934-b3821f711774.png)

**Comment by gernotstarke** [comment]
done, thx for spotting and telling us!
